### ISSUE TITLE
い

### ISSUE THREAD

**Issue by C0A21001** [syuhiroyoshi/ProjExD#10]
https://github.com/syuhiroyoshi/ProjExD/blob/1d4565056fc5e6e257faa90f373ed0216e3837d5/ex04/dodge_bomb.py#L91
残念ですの画面別に不要な画面が出てくる

**Comment by C0A21001** [comment]
> https://github.com/syuhiroyoshi/ProjExD/blob/1d4565056fc5e6e257faa90f373ed0216e3837d5/ex04/dodge_bomb.py#L91
> 
> 
> 残念ですの画面とは別に不要な画面が出てくる

**Comment by syuhiroyoshi** [comment]
ありがとうございます、不要な画面はもう隠した
